apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-fabric
        namespace: flux-fabric
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.187.170.165:8200
      role: vault-role
      authpath: fabricsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIPIvlBK1l92dYDHict3FPxFxzP+dZaCxMhm9pAvEwUyOEppeCpdeCpReCngKWggBEAEaBgiz
      gOGYBiIKc3lzY2hhbm5lbCpANzM3Njc4NzlkYmIxNTYwNmNjNWNmN2I4MTI2YzM5MGExMTRmMjMx
      M2I0NDg4OGNjYjcxMTc0ZWNkYWI1M2YwNBIaEhhLgmaEUCdO8+0F9+nKUnz8L3OqcyAS79gSl10K
      lF0SkV0SvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVSTDBFcW1RMlA2
      ZGRKNXF3VWxBNTFJakJTUm93Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJd09UQXhNRGN4T1RNNVdoY05NalV3TmpJeE1EY3hPVE01V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGSUVsNkpFYXJ3
      Y2FrSmREc0RlZm1zZnNEaEQzTXlsbG9sZwpTcWgwOHZieUQ5NkdhOVJ5UW12THpUV2tLSTg4cEw2
      M3M2RTFBbFZQN01TYlRwc1ltdXFqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1FQd2dyQmFWd0F1OGIKSW16R0lLY2dGd1Q4L0RB
      S0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTA5Y3hVZ3dlbjBlNTFYZmQ3ZEJHdGltdQpnanhSdVVU
      aWxOQVZBU3lQSHJ3Q0lHNElzUzRMNytKMmZ6bjBleWJpK2N2MGpoeENEVjNZalQ3Znl1MUR1UjlN
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFRENDQXJlZ0F3SUJBZ0lVQnUvUE41VlRvcVNmakc1WVlWdDNWK2hncTYwd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPVEF4TURjeU5qQXdXaGNO
      TWpNd09UQXhNRGN6TVRBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFSDFKdG1uSXV4YndFeUY1andkZXNsL01HNEY5WDVJRjMwVmNKRW9UYzdKMWlx
      cFNoajBzZQp6SGVzOG5lc05mR3RtdFlDTjRJaXJXanVwZ1FSMlhTay82T0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRK29wMWMx
      U0MrWE9Oc1VFZUpSTTFobVBvOWdqQWYKQmdOVkhTTUVHREFXZ0JTUVB3Z3JCYVZ3QXU4YkltekdJ
      S2NnRndUOC9EQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMlltUTBPRGM0WkRaa0xUaHNk
      R00xTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TkhBREJFCkFpQmNzdndneS9QMzJTbUcyUkhtR1I0NlB6dUJWTmdsTGFIVnE0MG9JY2RnWWdJZ0ZM
      L2pVVnN6WTVBVjhoOW0KbGQrVlUvWkc1Q2JsRThCemg3ZGFtY0lmTGJZPQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVSTDBFcW1RMlA2ZGRKNXF3VWxBNTFJakJTUm93Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd09UQXhNRGN4T1RNNVdo
      Y05NalV3TmpJeE1EY3hPVE01V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGSUVsNkpFYXJ3Y2FrSmREc0RlZm1zZnNEaEQzTXlsbG9s
      ZwpTcWgwOHZieUQ5NkdhOVJ5UW12THpUV2tLSTg4cEw2M3M2RTFBbFZQN01TYlRwc1ltdXFqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCU1FQd2dyQmFWd0F1OGIKSW16R0lLY2dGd1Q4L0RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QTA5Y3hVZ3dlbjBlNTFYZmQ3ZEJHdGltdQpnanhSdVVUaWxOQVZBU3lQSHJ3Q0lHNElzUzRMNytK
      MmZ6bjBleWJpK2N2MGpoeENEVjNZalQ3Znl1MUR1UjlNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVy
      TVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsU
      ErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrREND
      QVo2Z0F3SUJBZ0lVSU0rUVgrRnU1V3hNU3p3MzJJQytUcEMzeE1zd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qQTVNREV3TnpJd05EWmFGdzB5TlRBMk1qRXdOekl3TkRaYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVGxPaG9QV1NTT2lNYy93
      WmN1amhqbzNvVk9sb2lIQkM0Z0RCNVJwemFHZjRYSC9aQlBCejNQUkZqTTV3YloKNDcvQnMybUpH
      S0RHZmg1eXMreXByZkkxbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVhZ3ZjMXpXL3dBci9iZFhydnp4N3ZTNWxGV1F3Q2dZSUtv
      Wkl6ajBFCkF3SURTQUF3UlFJaEFQeEpGbGREaFFKajd5MCs0ZUZiYmxJb2Y3bHBGaHRuSlV1Mmhx
      bCtiM0IyQWlBd3FQaGUKUU9nZjVEZlpNd25VVzIzYXpIRWtKT3VKWnVVdlkwb2FEbGZuTGc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN2pDQ0FwU2dBd0lCQWdJVVBDRmxGYzhSYlFxYXVTNmFJMjhzV0doQkhZVXdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakE1TURFd056STNNREJhRncweU16QTVNREV3TnpNeU1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRbmpyRE80VllVUmVPa2x5N2tWbURlCjBS
      cDBhQlZFM0gwekNsVEYyakVnaEc5REttbHM2QnFZcDVRcFloY3g4WVYvQ1RBK29HNUN0OEVBN3Ru
      SmdDSE0KbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGRmxvR1ZYV1FPemNKUHJoNFlvSHNGam84TVhITUI4R0ExVWRJd1FZTUJh
      QUZHb0wzTmMxdjhBSy8yM1Y2Nzg4CmU3MHVaUlZrTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUWmpPV0ptTnpjME9EZ3ROWFJ0TkRZd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEU0FBd1JRSWhBSU81WVNTSDlwcWpSZDc4alJWMHdESmtMZm1xeGlaTFFrK1pKUEJH
      NHM2ZApBaUJvc3pXWWMvdklCZU1sdTl1Mk16NHFWcHRBTUlnZTNHY0JVSXFyUkVibVp3PT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVSU0rUVgrRnU1V3hNU3p3MzJJQytUcEMz
      eE1zd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2
      Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3
      RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTVNREV3TnpJd05EWmFGdzB5
      TlRBMk1qRXdOekl3TkRaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVr
      YjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVH
      QTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJC
      d05DCkFBVGxPaG9QV1NTT2lNYy93WmN1amhqbzNvVk9sb2lIQkM0Z0RCNVJwemFHZjRYSC9aQlBC
      ejNQUkZqTTV3YloKNDcvQnMybUpHS0RHZmg1eXMreXByZkkxbzBJd1FEQVBCZ05WSFJNQkFmOEVC
      VEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVhZ3ZjMXpXL3dBci9i
      ZFhydnp4N3ZTNWxGV1F3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFQeEpGbGREaFFKajd5MCs0
      ZUZiYmxJb2Y3bHBGaHRuSlV1MmhxbCtiM0IyQWlBd3FQaGUKUU9nZjVEZlpNd25VVzIzYXpIRWtK
      T3VKWnVVdlkwb2FEbGZuTGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQK
      BkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0Vu
      ZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1Jl
      YWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNo
      YW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxKNKwoHT3JkZXJlchKB
      KxLOFgoOc3VwcGx5Y2hhaW5NU1ASuxYaxxQKA01TUBK/FBK0FBKxFAoOc3VwcGx5Y2hhaW5NU1AS
      8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi96Q0NBYWFnQXdJQkFnSVVlYTUzbWtC
      VE9Ob05WeUpOeEFnZ2lnbWN1N2N3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhj
      Tk1qSXdPVEF4TURjeE9ETTBXaGNOTWpVd05qSXhNRGN4T0RNMFdqQmVNUXN3Q1FZRFZRUUdFd0pI
      UWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05W
      QkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJa
      TUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkd5Y2NiQ3VqRHd5V056djJqMzRZZE50
      RGxpMHB0dnQyK3Nxd1ZScmRiTkhwazFaUXU3dgpqMktlZ3ArN0cxaHEwOW4xbGdTZUYxUVZleVVl
      ZWRJQzkxU2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dt
      TUIwR0ExVWREZ1FXQkJRYS8yc29yTE9tYkNKelc2VkRObkJnN3d0Nk9UQUsKQmdncWhrak9QUVFE
      QWdOSEFEQkVBaUJ0WGp3cG1yUjFRcFg0dVlqbVNRUkpncmI0RHF3dEw3ZW5PS1cwQ2treQo3QUln
      Y0UxMUtodGg5cUVxeDY2d0JhMk5nS09jcmsrOFNURGhCVE1sYWtqWVlvWT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoipggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRqQ0NBb2ln
      QXdJQkFnSVVMbEJtV0srdFA5OU1pbytvSEU1THZWWlE2SVl3Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qSXdPVEF4TURjeU5UQXdXaGNOTWpNd09UQXhNRGN6TURBd1dqQnNN
      UXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVN
      UkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3R0ExVUVB
      d3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBEQVFjRFFnQUVnbTN5WkE0eHpWU3ZYbVgwYXdDTnljbjAxZVAwK2l2TwpoczdzNmJZVTdQK0pn
      M2loWisyREQrTVZ2T1BOMUhQZ2s0SHJvQWpMb1RCM2x1Z2UvdkRUWHFPQ0FSUXdnZ0VRCk1BNEdB
      MVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNVVzE3enp0
      N3AKU3VISWUrYWl2WmZxbkZzLzVqQWZCZ05WSFNNRUdEQVdnQlFhLzJzb3JMT21iQ0p6VzZWRE5u
      Qmc3d3Q2T1RBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAxTkRZNVpHUmpOMk5tTFcwNGJI
      RTFNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNu
      VmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpTENKb1pp
      NUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFpTENKb1pp
      NVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3ClJRSWhBSUdZaERWdkEz
      ZHdRbFMxQjBydDVZNFZJNmliUi9WbEdxOWsvNXl5cUtVZkFpQk9LWkxyK2ErUy9VS1cKejlEWDNY
      WXdINXJ4aXNmUVNvUTNCcWRVNW5HQ21RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoE
      U0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekNDQWFhZ0F3
      SUJBZ0lVZWE1M21rQlRPTm9OVnlKTnhBZ2dpZ21jdTdjd0NnWUlLb1pJemowRUF3SXcKWGpFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdG
      cGJpMXVaWFF3CkhoY05Nakl3T1RBeE1EY3hPRE0wV2hjTk1qVXdOakl4TURjeE9ETTBXakJlTVFz
      d0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1
      a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdO
      b1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJHeWNjYkN1akR3
      eVdOenYyajM0WWROdERsaTBwdHZ0MitzcXdWUnJkYk5IcGsxWlF1N3YKajJLZWdwKzdHMWhxMDlu
      MWxnU2VGMVFWZXlVZWVkSUM5MVNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWEvMnNvckxPbWJDSnpXNlZETm5CZzd3dDZPVEFL
      CkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCdFhqd3BtclIxUXBYNHVZam1TUVJKZ3JiNERxd3RMN2Vu
      T0tXMENra3kKN0FJZ2NFMTFLaHRoOXFFcXg2NndCYTJOZ0tPY3JrKzhTVERoQlRNbGFrallZb1k9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggS
      BggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIG
      CAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggB
      Eh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggB
      Eh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNo
      U2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1p
      bnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoI
      CgRWMl8wEgAaBkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlwZRLwERLlEQoIZXRjZHJhZnQS2BEKwREK
      GG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlEQWpDQ0FxbWdBd0lCQWdJVUNVa1A4ZVFLSk1sR2xDSkhySDlHUjk2ckhEa3dDZ1lJS29a
      SXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJK
      allTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09UQXhNRGN5TlRBd1doY05Nak13T1RB
      eE1EY3pNREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRB
      dU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21S
      bGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFWeFNOL0ZwNDNaRU4rUEp4U2pveThUSG8y
      CnJLSjUrb2t4VHZzN1hBUmZoS0NNcDBVM2thNnRkR1ZJVU82QTJGNVVWZ1h5eFdiZUNoWTRyMU9r
      TWIwbm80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NH
      QVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFp
      VWhzWndzdWlpWmlpaVJwcUpsdVFtNCs4Cnh6QWZCZ05WSFNNRUdEQVdnQlFhLzJzb3JMT21iQ0p6
      VzZWRE5uQmc3d3Q2T1RBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVH
      QndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5
      YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUK
      Vkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQ3NWSGVFbEVh
      TERtelY1cgpTYVU3Qmw5Skxtd3BjcWxBME54dGNQWmxSbHNDSUQxMXRlWnJHeHV1L2tPRWUxZjBF
      Ui9YU0tUZXJxblV4bW5QCmZQYzFJVnJxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVQ1VrUDhlUUtKTWxH
      bENKSHJIOUdSOTZySERrd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFO
      QmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQ
      Y21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3
      T1RBeE1EY3lOVEF3V2hjTk1qTXdPVEF4TURjek1EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIK
      TUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxj
      bVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpk
      WEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUVZ4
      U04vRnA0M1pFTitQSnhTam95OFRIbzIKcktKNStva3hUdnM3WEFSZmhLQ01wMFUza2E2dGRHVklV
      TzZBMkY1VVZnWHl4V2JlQ2hZNHIxT2tNYjBubzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURB
      Z09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJB
      ZjhFQWpBQU1CMEdBMVVkRGdRV0JCUWlVaHNad3N1aWlaaWlpUnBxSmx1UW00KzgKeHpBZkJnTlZI
      U01FR0RBV2dCUWEvMnNvckxPbWJDSnpXNlZETm5CZzd3dDZPVEEvQmdOVkhSRUVPREEyZ2hodgpj
      bVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJH
      OWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FX
      RjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NH
      eDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpq
      MEVBd0lEUndBd1JBSWdDc1ZIZUVsRWFMRG16VjVyClNhVTdCbDlKTG13cGNxbEEwTnh0Y1BabFJs
      c0NJRDExdGVackd4dXUva09FZTFmMEVSL1hTS1RlcnFuVXhtblAKZlBjMUlWcnEKLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRtaW5zIiIKB1dyaXRlcnMS
      FxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRt
      aW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhIS
      CAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8a
      BkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0
      OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJf
      MBIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
